name: ai_notes
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  path_provider: ^2.0.13
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  intl: ^0.19.0
  fluttertoast: ^8.2.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  sizer: ^2.0.15
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  google_generative_ai: ^0.4.4
  animated_bottom_navigation_bar: ^1.3.3
  flutter_staggered_grid_view: ^0.7.0
  local_auth: ^2.3.0

dev_dependencies:
  hive_generator:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
